// GENERATED by scripts/gen-sgp4-reference-vectors.py — do not edit by hand.
// In-app mirror of tests/golden/sgp4-reference-vectors.json: the independent
// python-sgp4 (Vallado AIAA 2006) reference ECI vectors. The WS-G provenance
// popover renders these app-value-vs-reference side by side. Kept byte-identical
// to the golden by tests/unit/sgp4-reference-vectors-bundle-sync.test.mjs.

export interface Sgp4ReferenceSample {
  readonly label: string;
  readonly orbitClass: "LEO" | "MEO" | "GEO";
  readonly noradId: number;
  readonly line1: string;
  readonly line2: string;
  readonly timeUtc: string;
  readonly positionEciKm: { readonly x: number; readonly y: number; readonly z: number };
  readonly velocityEciKmPerSec: { readonly x: number; readonly y: number; readonly z: number };
}

export interface Sgp4ReferenceVectors {
  readonly reference: {
    readonly generator: string;
    readonly generatorVersion: string;
    readonly algorithm: string;
    readonly gravityModel: string;
    readonly independentFrom: string;
  };
  readonly toleranceKm: number;
  readonly samples: ReadonlyArray<Sgp4ReferenceSample>;
}

export const SGP4_REFERENCE_VECTORS: Sgp4ReferenceVectors = {
  "reference": {
    "generator": "python-sgp4",
    "generatorVersion": "2.25",
    "algorithm": "SGP4 (Vallado et al., AIAA 2006 reference implementation)",
    "gravityModel": "WGS72",
    "independentFrom": "satellite.js (the app's propagator)"
  },
  "toleranceKm": 1.0,
  "samples": [
    {
      "label": "ONEWEB-0012",
      "orbitClass": "LEO",
      "noradId": 44057,
      "line1": "1 44057U 19010A   26164.90931097  .00000066  00000+0  13814-3 0  9999",
      "line2": "2 44057  87.9097 229.4364 0002037  86.1004 274.0360 13.16594739351136",
      "timeUtc": "2026-06-15T00:00:00.000Z",
      "positionEciKm": {
        "x": 3132.271859656286,
        "y": 3292.8091253435264,
        "z": 6053.812302774234
      },
      "velocityEciKmPerSec": {
        "x": 3.6763233887972304,
        "y": 4.504528223970147,
        "z": -4.342280345409697
      }
    },
    {
      "label": "ONEWEB-0012",
      "orbitClass": "LEO",
      "noradId": 44057,
      "line1": "1 44057U 19010A   26164.90931097  .00000066  00000+0  13814-3 0  9999",
      "line2": "2 44057  87.9097 229.4364 0002037  86.1004 274.0360 13.16594739351136",
      "timeUtc": "2026-06-15T03:00:00.000Z",
      "positionEciKm": {
        "x": -4956.023731015358,
        "y": -5731.396651809082,
        "z": -164.04391467920397
      },
      "velocityEciKmPerSec": {
        "x": 0.10299525786990954,
        "y": -0.28524232661455406,
        "z": 7.247244986570752
      }
    },
    {
      "label": "ONEWEB-0012",
      "orbitClass": "LEO",
      "noradId": 44057,
      "line1": "1 44057U 19010A   26164.90931097  .00000066  00000+0  13814-3 0  9999",
      "line2": "2 44057  87.9097 229.4364 0002037  86.1004 274.0360 13.16594739351136",
      "timeUtc": "2026-06-15T06:00:00.000Z",
      "positionEciKm": {
        "x": 2949.9488813144567,
        "y": 3743.4579180983374,
        "z": -5899.488801418493
      },
      "velocityEciKmPerSec": {
        "x": -3.8107571864319403,
        "y": -4.1564909026445145,
        "z": -4.546240172010576
      }
    },
    {
      "label": "GSAT0101 (GALILEO-PFM)",
      "orbitClass": "MEO",
      "noradId": 37846,
      "line1": "1 37846U 11060A   26163.74233043 -.00000071  00000+0  00000+0 0  9997",
      "line2": "2 37846  56.9957 341.8816 0003117  51.3749 308.6629  1.70475562 91048",
      "timeUtc": "2026-06-15T00:00:00.000Z",
      "positionEciKm": {
        "x": 12275.386076508994,
        "y": -17845.33332294075,
        "z": -20186.058720002686
      },
      "velocityEciKmPerSec": {
        "x": 3.196812119307886,
        "y": 0.17524693543089928,
        "z": 1.7912809755065813
      }
    },
    {
      "label": "GSAT0101 (GALILEO-PFM)",
      "orbitClass": "MEO",
      "noradId": 37846,
      "line1": "1 37846U 11060A   26163.74233043 -.00000071  00000+0  00000+0 0  9997",
      "line2": "2 37846  56.9957 341.8816 0003117  51.3749 308.6629  1.70475562 91048",
      "timeUtc": "2026-06-15T03:00:00.000Z",
      "positionEciKm": {
        "x": 27917.190495679428,
        "y": -2728.0514489562925,
        "z": 9420.864219916208
      },
      "velocityEciKmPerSec": {
        "x": -0.7477571410822658,
        "y": 2.1936017448699547,
        "z": 2.846912369055913
      }
    },
    {
      "label": "GSAT0101 (GALILEO-PFM)",
      "orbitClass": "MEO",
      "noradId": 37846,
      "line1": "1 37846U 11060A   26163.74233043 -.00000071  00000+0  00000+0 0  9997",
      "line2": "2 37846  56.9957 341.8816 0003117  51.3749 308.6629  1.70475562 91048",
      "timeUtc": "2026-06-15T06:00:00.000Z",
      "positionEciKm": {
        "x": 525.1131022359154,
        "y": 16588.159324209988,
        "z": 24494.45701736458
      },
      "velocityEciKmPerSec": {
        "x": -3.542428794732003,
        "y": 0.831755193374022,
        "z": -0.4861469847810426
      }
    },
    {
      "label": "TDRS 3",
      "orbitClass": "GEO",
      "noradId": 19548,
      "line1": "1 19548U 88091B   26164.89471543 -.00000298  00000+0  00000+0 0  9991",
      "line2": "2 19548  12.6045 341.0236 0038404 356.0041 198.4347  1.00274232125357",
      "timeUtc": "2026-06-15T00:00:00.000Z",
      "positionEciKm": {
        "x": -34723.59245062553,
        "y": -22913.262265434547,
        "z": -7380.450150046357
      },
      "velocityEciKmPerSec": {
        "x": 1.742516223103649,
        "y": -2.4935017832562223,
        "z": -0.40077401378108957
      }
    },
    {
      "label": "TDRS 3",
      "orbitClass": "GEO",
      "noradId": 19548,
      "line1": "1 19548U 88091B   26164.89471543 -.00000298  00000+0  00000+0 0  9991",
      "line2": "2 19548  12.6045 341.0236 0038404 356.0041 198.4347  1.00274232125357",
      "timeUtc": "2026-06-15T03:00:00.000Z",
      "positionEciKm": {
        "x": -7597.942906416299,
        "y": -40425.94719092768,
        "z": -9110.025972074349
      },
      "velocityEciKmPerSec": {
        "x": 3.02082688061642,
        "y": -0.5778303713720998,
        "z": 0.09786942584344176
      }
    },
    {
      "label": "TDRS 3",
      "orbitClass": "GEO",
      "noradId": 19548,
      "line1": "1 19548U 88091B   26164.89471543 -.00000298  00000+0  00000+0 0  9991",
      "line2": "2 19548  12.6045 341.0236 0038404 356.0041 198.4347  1.00274232125357",
      "timeUtc": "2026-06-15T06:00:00.000Z",
      "positionEciKm": {
        "x": 23984.461248120384,
        "y": -34077.56188013602,
        "z": -5464.548543797161
      },
      "velocityEciKmPerSec": {
        "x": 2.519840687378453,
        "y": 1.6944357883754757,
        "z": 0.5423004695439048
      }
    }
  ]
};
