// GENERATED by scripts/gen-sgp4-reference-vectors.py — do not edit by hand.
// In-app mirror of tests/golden/sgp4-reference-vectors.json: the independent
// python-sgp4 (Vallado AIAA 2006) reference ECI vectors. The WS-G provenance
// popover renders these app-value-vs-reference side by side. Kept byte-identical
// to the golden by tests/unit/sgp4-reference-vectors-bundle-sync.test.mjs.

export interface Sgp4ReferenceSample {
  readonly label: string;
  readonly orbitClass: "LEO" | "MEO" | "GEO";
  readonly noradId: number;
  readonly line1: string;
  readonly line2: string;
  readonly timeUtc: string;
  readonly positionEciKm: { readonly x: number; readonly y: number; readonly z: number };
  readonly velocityEciKmPerSec: { readonly x: number; readonly y: number; readonly z: number };
}

export interface Sgp4ReferenceVectors {
  readonly reference: {
    readonly generator: string;
    readonly generatorVersion: string;
    readonly algorithm: string;
    readonly gravityModel: string;
    readonly independentFrom: string;
  };
  readonly toleranceKm: number;
  readonly samples: ReadonlyArray<Sgp4ReferenceSample>;
}

export const SGP4_REFERENCE_VECTORS: Sgp4ReferenceVectors = {
  "reference": {
    "generator": "python-sgp4",
    "generatorVersion": "2.25",
    "algorithm": "SGP4 (Vallado et al., AIAA 2006 reference implementation)",
    "gravityModel": "WGS72",
    "independentFrom": "satellite.js (the app's propagator)"
  },
  "toleranceKm": 1.0,
  "samples": [
    {
      "label": "ONEWEB-0012",
      "orbitClass": "LEO",
      "noradId": 44057,
      "line1": "1 44057U 19010A   26164.90931097  .00000066  00000+0  13814-3 0  9999",
      "line2": "2 44057  87.9097 229.4364 0002037  86.1004 274.0360 13.16594739351136",
      "timeUtc": "2026-05-17T00:00:00.000Z",
      "positionEciKm": {
        "x": -452.61728210254455,
        "y": -164.2897490737566,
        "z": -7568.63911583657
      },
      "velocityEciKmPerSec": {
        "x": -4.137980043678536,
        "y": -5.929517051183708,
        "z": 0.37487235198980356
      }
    },
    {
      "label": "ONEWEB-0012",
      "orbitClass": "LEO",
      "noradId": 44057,
      "line1": "1 44057U 19010A   26164.90931097  .00000066  00000+0  13814-3 0  9999",
      "line2": "2 44057  87.9097 229.4364 0002037  86.1004 274.0360 13.16594739351136",
      "timeUtc": "2026-05-17T03:00:00.000Z",
      "positionEciKm": {
        "x": 3698.280475173344,
        "y": 4998.429876422205,
        "z": 4321.478084372097
      },
      "velocityEciKmPerSec": {
        "x": 2.2059075557355943,
        "y": 3.52327294796141,
        "z": -5.948832739747959
      }
    },
    {
      "label": "ONEWEB-0012",
      "orbitClass": "LEO",
      "noradId": 44057,
      "line1": "1 44057U 19010A   26164.90931097  .00000066  00000+0  13814-3 0  9999",
      "line2": "2 44057  87.9097 229.4364 0002037  86.1004 274.0360 13.16594739351136",
      "timeUtc": "2026-05-17T06:00:00.000Z",
      "positionEciKm": {
        "x": -4094.6065409316247,
        "y": -5974.561543306386,
        "z": 2226.829068213219
      },
      "velocityEciKmPerSec": {
        "x": 1.4374703955903618,
        "y": 1.6080370163504554,
        "z": 6.925940832835077
      }
    },
    {
      "label": "GSAT0101 (GALILEO-PFM)",
      "orbitClass": "MEO",
      "noradId": 37846,
      "line1": "1 37846U 11060A   26163.74233043 -.00000071  00000+0  00000+0 0  9997",
      "line2": "2 37846  56.9957 341.8816 0003117  51.3749 308.6629  1.70475562 91048",
      "timeUtc": "2026-05-17T00:00:00.000Z",
      "positionEciKm": {
        "x": -21316.681769641542,
        "y": 15691.014777454926,
        "z": 13245.130716755817
      },
      "velocityEciKmPerSec": {
        "x": -2.3756087013032703,
        "y": -1.0277061941921473,
        "z": -2.601671109757718
      }
    },
    {
      "label": "GSAT0101 (GALILEO-PFM)",
      "orbitClass": "MEO",
      "noradId": 37846,
      "line1": "1 37846U 11060A   26163.74233043 -.00000071  00000+0  00000+0 0  9997",
      "line2": "2 37846  56.9957 341.8816 0003117  51.3749 308.6629  1.70475562 91048",
      "timeUtc": "2026-05-17T03:00:00.000Z",
      "positionEciKm": {
        "x": -23557.10853359983,
        "y": -4460.233332087244,
        "z": -17382.27901447804
      },
      "velocityEciKmPerSec": {
        "x": 2.0233651469744145,
        "y": -2.129230387949947,
        "z": -2.1968492547681757
      }
    },
    {
      "label": "GSAT0101 (GALILEO-PFM)",
      "orbitClass": "MEO",
      "noradId": 37846,
      "line1": "1 37846U 11060A   26163.74233043 -.00000071  00000+0  00000+0 0  9997",
      "line2": "2 37846  56.9957 341.8816 0003117  51.3749 308.6629  1.70475562 91048",
      "timeUtc": "2026-05-17T06:00:00.000Z",
      "positionEciKm": {
        "x": 10454.884143098549,
        "y": -17753.508136878518,
        "z": -21264.467372604864
      },
      "velocityEciKmPerSec": {
        "x": 3.3062982510321786,
        "y": 0.046387550704203244,
        "z": 1.5888224420141568
      }
    },
    {
      "label": "TDRS 3",
      "orbitClass": "GEO",
      "noradId": 19548,
      "line1": "1 19548U 88091B   26164.89471543 -.00000298  00000+0  00000+0 0  9991",
      "line2": "2 19548  12.6045 341.0236 0038404 356.0041 198.4347  1.00274232125357",
      "timeUtc": "2026-05-17T00:00:00.000Z",
      "positionEciKm": {
        "x": -42010.661069652895,
        "y": -3271.403238293193,
        "z": -3734.9452817998936
      },
      "velocityEciKmPerSec": {
        "x": 0.2926654918544783,
        "y": -2.9883395716991705,
        "z": -0.6125309239170433
      }
    },
    {
      "label": "TDRS 3",
      "orbitClass": "GEO",
      "noradId": 19548,
      "line1": "1 19548U 88091B   26164.89471543 -.00000298  00000+0  00000+0 0  9991",
      "line2": "2 19548  12.6045 341.0236 0038404 356.0041 198.4347  1.00274232125357",
      "timeUtc": "2026-05-17T03:00:00.000Z",
      "positionEciKm": {
        "x": -26889.95552379843,
        "y": -31376.57954405049,
        "z": -8600.264273715668
      },
      "velocityEciKmPerSec": {
        "x": 2.3645768215248872,
        "y": -1.9452314632713834,
        "z": -0.24132950742297535
      }
    },
    {
      "label": "TDRS 3",
      "orbitClass": "GEO",
      "noradId": 19548,
      "line1": "1 19548U 88091B   26164.89471543 -.00000298  00000+0  00000+0 0  9991",
      "line2": "2 19548  12.6045 341.0236 0038404 356.0041 198.4347  1.00274232125357",
      "timeUtc": "2026-05-17T06:00:00.000Z",
      "positionEciKm": {
        "x": 3999.7511845245685,
        "y": -41041.03527409028,
        "z": -8413.508071570534
      },
      "velocityEciKmPerSec": {
        "x": 3.0576806897492674,
        "y": 0.25229387034001843,
        "z": 0.2748696941593568
      }
    }
  ]
};
