// Drift guard for the demo scenario single source of truth.
//
// demo-scenario-config.json declares the demo window. Several artifacts are
// FROZEN COMPUTED values (not date strings): the golden SGP4 ECI sample vectors,
// their in-app mirror, and the wave handover baselines. They cannot auto-follow
// the config — they must be REGENERATED when the window changes. This test fails
// loudly if any frozen artifact's embedded timestamp falls outside the window
// the config currently declares, catching a config bump that forgot the regen.
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import config from "../../src/features/multi-station-selector/demo-scenario-config.json" with { type: "json" };
import golden from "../golden/sgp4-reference-vectors.json" with { type: "json" };

const startMs = Date.parse(config.windowStartUtc);
const endMs = startMs + config.windowDurationMinutes * 60_000;
const windowLabel = `[${config.windowStartUtc} +${config.windowDurationMinutes}m]`;

function within(iso) {
  const ms = Date.parse(iso);
  return Number.isFinite(ms) && ms >= startMs && ms <= endMs;
}

function readRepo(rel) {
  return readFileSync(fileURLToPath(new URL(`../../${rel}`, import.meta.url)), "utf8");
}

test("config window is internally well-formed", () => {
  assert.ok(Number.isFinite(startMs), "windowStartUtc parses");
  assert.ok(config.windowDurationMinutes > 0, "windowDurationMinutes positive");
  for (const orbit of ["LEO", "MEO", "GEO"]) {
    assert.ok(
      typeof config.tleSnapshots?.[orbit] === "string" && config.tleSnapshots[orbit].length > 0,
      `tleSnapshots.${orbit} present`
    );
  }
});

test("golden SGP4 sample times stay inside the configured demo window", () => {
  assert.ok(Array.isArray(golden.samples) && golden.samples.length > 0, "golden has samples");
  for (const s of golden.samples) {
    assert.ok(
      within(s.timeUtc),
      `golden sample ${s.label} timeUtc ${s.timeUtc} is outside the demo window ${windowLabel}. ` +
        `Regenerate goldens (python3 scripts/gen-sgp4-reference-vectors.py) after editing demo-scenario-config.json.`
    );
  }
});

test("frozen TS artifacts' embedded timestamps stay inside the configured demo window", () => {
  // NOTE: v4-projection-wave1-baselines.ts is intentionally EXCLUDED. It is a
  // frozen pre-wave-2 historical comparison baseline (see its header) whose
  // timestamps deliberately do NOT track the demo window; gating it here would
  // force a semantically-wrong regeneration. Only window-tracking artifacts
  // (regenerated by gen-sgp4-reference-vectors.py) are guarded.
  const targets = [
    {
      rel: "src/features/multi-station-selector/sgp4-reference-vectors.ts",
      re: /"timeUtc":\s*"([^"]+)"/g
    }
  ];
  for (const { rel, re } of targets) {
    const found = [...readRepo(rel).matchAll(re)].map((m) => m[1]);
    assert.ok(found.length > 0, `${rel}: no embedded timestamps found (field regex stale?)`);
    for (const iso of found) {
      assert.ok(
        within(iso),
        `${rel}: ${iso} is outside the demo window ${windowLabel}. ` +
          `Regenerate the frozen artifact after editing demo-scenario-config.json.`
      );
    }
  }
});
