// WS-E E3 — SGP4 reference-vector cross-check.
//
// The app propagates TLEs with satellite.js. This test feeds the SAME TLEs at
// the SAME UTC instants to satellite.js and asserts the result matches an
// INDEPENDENT reference produced by python-sgp4 (Vallado AIAA 2006 C++), stored
// in tests/golden/sgp4-reference-vectors.json (generated by
// scripts/gen-sgp4-reference-vectors.py). Agreement to within tolerance is the
// proof that the in-app TLE->ECI propagation does the real published math — a
// faker would have to coincidentally match an independent SGP4, i.e. do the
// math. The same golden artifact backs the WS-G provenance trace inspector.
import test from "node:test";
import assert from "node:assert/strict";
import { propagate, twoline2satrec } from "satellite.js";

import reference from "../golden/sgp4-reference-vectors.json" with { type: "json" };

const magnitude = (v) => Math.sqrt(v.x * v.x + v.y * v.y + v.z * v.z);
const delta = (a, b) => Math.sqrt((a.x - b.x) ** 2 + (a.y - b.y) ** 2 + (a.z - b.z) ** 2);

test("reference artifact is the expected independent shape", () => {
  assert.equal(reference.schema, "sgp4-reference-vectors/v1");
  assert.equal(reference.reference.generator, "python-sgp4");
  assert.equal(reference.reference.gravityModel, "WGS72");
  assert.ok(reference.samples.length >= 9, "expected at least 3 satellites x 3 times");
});

test("satellite.js reproduces the independent python-sgp4 ECI vectors within tolerance", () => {
  const tol = reference.toleranceKm;
  let maxPosDelta = 0;
  for (const sample of reference.samples) {
    const satrec = twoline2satrec(sample.line1, sample.line2);
    const result = propagate(satrec, new Date(sample.timeUtc));
    assert.ok(result && result.position, `propagation failed for ${sample.label} @ ${sample.timeUtc}`);

    const posDelta = delta(result.position, sample.positionEciKm);
    const velDelta = delta(result.velocity, sample.velocityEciKmPerSec);
    maxPosDelta = Math.max(maxPosDelta, posDelta);

    assert.ok(
      posDelta < tol,
      `${sample.label} @ ${sample.timeUtc}: position delta ${posDelta.toFixed(6)} km exceeds tolerance ${tol} km`,
    );
    assert.ok(velDelta < tol, `${sample.label} @ ${sample.timeUtc}: velocity delta ${velDelta.toFixed(6)} km/s exceeds tolerance`);
  }
  // The agreement is far tighter than the contract tolerance — surface it so the
  // proof is visible in the test log (typically sub-metre).
  console.log(`  [E3] max satellite.js vs python-sgp4 position delta: ${(maxPosDelta * 1000).toFixed(3)} m`);
  assert.ok(maxPosDelta < 0.05, `max position delta ${maxPosDelta} km should be << 1 km (sub-50 m)`);
});

test("propagated radii are physically sane for each orbit class", () => {
  const radiusByClass = {};
  for (const sample of reference.samples) {
    (radiusByClass[sample.orbitClass] ??= []).push(magnitude(sample.positionEciKm));
  }
  // LEO ~ 6.9e3 km radius, MEO ~ 2.9e4 km, GEO ~ 4.2e4 km (geosynchronous).
  for (const r of radiusByClass.LEO ?? []) assert.ok(r > 6700 && r < 8200, `LEO radius ${r}`);
  for (const r of radiusByClass.MEO ?? []) assert.ok(r > 27000 && r < 31000, `MEO radius ${r}`);
  for (const r of radiusByClass.GEO ?? []) assert.ok(r > 41000 && r < 43000, `GEO radius ${r}`);
});
